// ============================================================
// ID-SYSTEM.JS (refactored)
//
// KEY CHANGE: IDs are now server-generated UUIDs (gen_random_uuid()
// in Supabase). The client no longer generates IDs at all.
//
// What remains:
//   - UUID validation helpers
//   - String comparison utilities
//   - IdTracker (kept for backward-compat, uses crypto.randomUUID)
// ============================================================

// UUID v4 regex
const UUID_RE = /^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;

/**
 * Generate a client-side UUID.
 * Used ONLY as a temporary local ID before the server confirms the real UUID.
 * Never persisted directly — always replaced by the Supabase-returned id.
 *
 * Uses crypto.randomUUID() (CSPRNG) — NOT Date.now() or Math.random().
 */
export function generateTempId() {
    return crypto.randomUUID();
}

/** Check whether a string is a valid UUID v4. */
export function isUUID(str) {
    return typeof str === 'string' && UUID_RE.test(str);
}

/** Normalize an ID to string for consistent Map key usage. */
export function normalizeId(id) {
    return id ? String(id) : null;
}

/** Compare two IDs safely (handles string/number mismatches). */
export function idsEqual(id1, id2) {
    return normalizeId(id1) === normalizeId(id2);
}

/**
 * IdTracker — tracks UUIDs in a Set for collision checking.
 * Kept for backward-compat with code that used it for ID generation.
 * Now it only validates and tracks — it never generates predictable IDs.
 */
export class IdTracker {
    constructor() { this.ids = new Set(); }

    add(id)        { if (id) this.ids.add(String(id)); }
    has(id)        { return this.ids.has(String(id)); }

    /** Generate a truly random UUID (not Date.now-based). */
    generate()     { return generateTempId(); }

    loadFromTeams(teams)   { (teams   || []).forEach(t => { this.add(t.id); (t.speakers || []).forEach(s => this.add(s.id)); }); }
    loadFromJudges(judges) { (judges  || []).forEach(j => this.add(j.id)); }
    loadFromRounds(rounds) { (rounds  || []).forEach(r => { this.add(r.id); (r.debates || []).forEach(d => this.add(d.id)); }); }
}

// ── REMOVED: Date.now()-based generation ─────────────────────────────────────
// The original generateId(prefix, existingIds) function used:
//   Date.now().toString(36) + Math.random().toString(36).substr(2, 8)
//
// This is INSECURE because:
//   1. Timestamp-based IDs are enumerable (attacker can iterate IDs)
//   2. Math.random() is not a CSPRNG — can be predicted in some environments
//   3. IDs created within the same millisecond can collide
//
// All entity IDs are now:
//   - Generated by PostgreSQL: DEFAULT gen_random_uuid()
//   - Returned by Supabase after INSERT
//   - UUID v4 format: cryptographically random, globally unique
